/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BlocXSocial {
  export type CommentStruct = {
    id: BigNumberish;
    postId: BigNumberish;
    author: AddressLike;
    contentHash: string;
    timestamp: BigNumberish;
    isDeleted: boolean;
  };

  export type CommentStructOutput = [
    id: bigint,
    postId: bigint,
    author: string,
    contentHash: string,
    timestamp: bigint,
    isDeleted: boolean
  ] & {
    id: bigint;
    postId: bigint;
    author: string;
    contentHash: string;
    timestamp: bigint;
    isDeleted: boolean;
  };
}

export interface BlocXSocialInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LIKE_THRESHOLD"
      | "REWARD_PER_LIKE"
      | "commentIndex"
      | "commentPostId"
      | "createComment"
      | "createPost"
      | "deleteComment"
      | "deletePost"
      | "editPost"
      | "getAllComments"
      | "getComment"
      | "getCommentCount"
      | "hasLiked"
      | "likePost"
      | "posts"
      | "profileContract"
      | "tokenContract"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CommentCreated"
      | "CommentDeleted"
      | "PostCreated"
      | "PostDeleted"
      | "PostEdited"
      | "PostLiked"
      | "RewardIssued"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LIKE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARD_PER_LIKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "commentIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commentPostId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createComment",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "createPost", values: [string]): string;
  encodeFunctionData(
    functionFragment: "deleteComment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deletePost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "editPost",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllComments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getComment",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommentCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasLiked",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "likePost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "posts", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "profileContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenContract",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "LIKE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_PER_LIKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commentIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commentPostId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createComment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteComment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deletePost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "editPost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllComments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getComment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCommentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasLiked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "likePost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "posts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "profileContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenContract",
    data: BytesLike
  ): Result;
}

export namespace CommentCreatedEvent {
  export type InputTuple = [
    commentId: BigNumberish,
    postId: BigNumberish,
    author: AddressLike,
    contentHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    commentId: bigint,
    postId: bigint,
    author: string,
    contentHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    commentId: bigint;
    postId: bigint;
    author: string;
    contentHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommentDeletedEvent {
  export type InputTuple = [
    commentId: BigNumberish,
    postId: BigNumberish,
    deletedBy: AddressLike
  ];
  export type OutputTuple = [
    commentId: bigint,
    postId: bigint,
    deletedBy: string
  ];
  export interface OutputObject {
    commentId: bigint;
    postId: bigint;
    deletedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostCreatedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    author: AddressLike,
    contentHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    postId: bigint,
    author: string,
    contentHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    postId: bigint;
    author: string;
    contentHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostDeletedEvent {
  export type InputTuple = [postId: BigNumberish, author: AddressLike];
  export type OutputTuple = [postId: bigint, author: string];
  export interface OutputObject {
    postId: bigint;
    author: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostEditedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    author: AddressLike,
    newContentHash: string
  ];
  export type OutputTuple = [
    postId: bigint,
    author: string,
    newContentHash: string
  ];
  export interface OutputObject {
    postId: bigint;
    author: string;
    newContentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostLikedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    liker: AddressLike,
    newLikeCount: BigNumberish
  ];
  export type OutputTuple = [
    postId: bigint,
    liker: string,
    newLikeCount: bigint
  ];
  export interface OutputObject {
    postId: bigint;
    liker: string;
    newLikeCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardIssuedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    author: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [postId: bigint, author: string, amount: bigint];
  export interface OutputObject {
    postId: bigint;
    author: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlocXSocial extends BaseContract {
  connect(runner?: ContractRunner | null): BlocXSocial;
  waitForDeployment(): Promise<this>;

  interface: BlocXSocialInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LIKE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  REWARD_PER_LIKE: TypedContractMethod<[], [bigint], "view">;

  commentIndex: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  commentPostId: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  createComment: TypedContractMethod<
    [_postId: BigNumberish, _contentHash: string],
    [void],
    "nonpayable"
  >;

  createPost: TypedContractMethod<[_contentHash: string], [void], "nonpayable">;

  deleteComment: TypedContractMethod<
    [_commentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  deletePost: TypedContractMethod<
    [_postId: BigNumberish],
    [void],
    "nonpayable"
  >;

  editPost: TypedContractMethod<
    [_postId: BigNumberish, _newContentHash: string],
    [void],
    "nonpayable"
  >;

  getAllComments: TypedContractMethod<
    [_postId: BigNumberish],
    [BlocXSocial.CommentStructOutput[]],
    "view"
  >;

  getComment: TypedContractMethod<
    [_postId: BigNumberish, _index: BigNumberish],
    [BlocXSocial.CommentStructOutput],
    "view"
  >;

  getCommentCount: TypedContractMethod<
    [_postId: BigNumberish],
    [bigint],
    "view"
  >;

  hasLiked: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  likePost: TypedContractMethod<[_postId: BigNumberish], [void], "nonpayable">;

  posts: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, boolean] & {
        id: bigint;
        author: string;
        contentHash: string;
        likeCount: bigint;
        commentCount: bigint;
        rewardMilestone: bigint;
        timestamp: bigint;
        isDeleted: boolean;
      }
    ],
    "view"
  >;

  profileContract: TypedContractMethod<[], [string], "view">;

  tokenContract: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LIKE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REWARD_PER_LIKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "commentIndex"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "commentPostId"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "createComment"
  ): TypedContractMethod<
    [_postId: BigNumberish, _contentHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createPost"
  ): TypedContractMethod<[_contentHash: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteComment"
  ): TypedContractMethod<[_commentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deletePost"
  ): TypedContractMethod<[_postId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "editPost"
  ): TypedContractMethod<
    [_postId: BigNumberish, _newContentHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllComments"
  ): TypedContractMethod<
    [_postId: BigNumberish],
    [BlocXSocial.CommentStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getComment"
  ): TypedContractMethod<
    [_postId: BigNumberish, _index: BigNumberish],
    [BlocXSocial.CommentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCommentCount"
  ): TypedContractMethod<[_postId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasLiked"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "likePost"
  ): TypedContractMethod<[_postId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "posts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, boolean] & {
        id: bigint;
        author: string;
        contentHash: string;
        likeCount: bigint;
        commentCount: bigint;
        rewardMilestone: bigint;
        timestamp: bigint;
        isDeleted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "profileContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenContract"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CommentCreated"
  ): TypedContractEvent<
    CommentCreatedEvent.InputTuple,
    CommentCreatedEvent.OutputTuple,
    CommentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CommentDeleted"
  ): TypedContractEvent<
    CommentDeletedEvent.InputTuple,
    CommentDeletedEvent.OutputTuple,
    CommentDeletedEvent.OutputObject
  >;
  getEvent(
    key: "PostCreated"
  ): TypedContractEvent<
    PostCreatedEvent.InputTuple,
    PostCreatedEvent.OutputTuple,
    PostCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PostDeleted"
  ): TypedContractEvent<
    PostDeletedEvent.InputTuple,
    PostDeletedEvent.OutputTuple,
    PostDeletedEvent.OutputObject
  >;
  getEvent(
    key: "PostEdited"
  ): TypedContractEvent<
    PostEditedEvent.InputTuple,
    PostEditedEvent.OutputTuple,
    PostEditedEvent.OutputObject
  >;
  getEvent(
    key: "PostLiked"
  ): TypedContractEvent<
    PostLikedEvent.InputTuple,
    PostLikedEvent.OutputTuple,
    PostLikedEvent.OutputObject
  >;
  getEvent(
    key: "RewardIssued"
  ): TypedContractEvent<
    RewardIssuedEvent.InputTuple,
    RewardIssuedEvent.OutputTuple,
    RewardIssuedEvent.OutputObject
  >;

  filters: {
    "CommentCreated(uint256,uint256,address,string,uint256)": TypedContractEvent<
      CommentCreatedEvent.InputTuple,
      CommentCreatedEvent.OutputTuple,
      CommentCreatedEvent.OutputObject
    >;
    CommentCreated: TypedContractEvent<
      CommentCreatedEvent.InputTuple,
      CommentCreatedEvent.OutputTuple,
      CommentCreatedEvent.OutputObject
    >;

    "CommentDeleted(uint256,uint256,address)": TypedContractEvent<
      CommentDeletedEvent.InputTuple,
      CommentDeletedEvent.OutputTuple,
      CommentDeletedEvent.OutputObject
    >;
    CommentDeleted: TypedContractEvent<
      CommentDeletedEvent.InputTuple,
      CommentDeletedEvent.OutputTuple,
      CommentDeletedEvent.OutputObject
    >;

    "PostCreated(uint256,address,string,uint256)": TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;
    PostCreated: TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;

    "PostDeleted(uint256,address)": TypedContractEvent<
      PostDeletedEvent.InputTuple,
      PostDeletedEvent.OutputTuple,
      PostDeletedEvent.OutputObject
    >;
    PostDeleted: TypedContractEvent<
      PostDeletedEvent.InputTuple,
      PostDeletedEvent.OutputTuple,
      PostDeletedEvent.OutputObject
    >;

    "PostEdited(uint256,address,string)": TypedContractEvent<
      PostEditedEvent.InputTuple,
      PostEditedEvent.OutputTuple,
      PostEditedEvent.OutputObject
    >;
    PostEdited: TypedContractEvent<
      PostEditedEvent.InputTuple,
      PostEditedEvent.OutputTuple,
      PostEditedEvent.OutputObject
    >;

    "PostLiked(uint256,address,uint256)": TypedContractEvent<
      PostLikedEvent.InputTuple,
      PostLikedEvent.OutputTuple,
      PostLikedEvent.OutputObject
    >;
    PostLiked: TypedContractEvent<
      PostLikedEvent.InputTuple,
      PostLikedEvent.OutputTuple,
      PostLikedEvent.OutputObject
    >;

    "RewardIssued(uint256,address,uint256)": TypedContractEvent<
      RewardIssuedEvent.InputTuple,
      RewardIssuedEvent.OutputTuple,
      RewardIssuedEvent.OutputObject
    >;
    RewardIssued: TypedContractEvent<
      RewardIssuedEvent.InputTuple,
      RewardIssuedEvent.OutputTuple,
      RewardIssuedEvent.OutputObject
    >;
  };
}
