/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BlocXSocialInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LIKE_THRESHOLD"
      | "REWARD_PER_LIKE"
      | "createPost"
      | "hasLiked"
      | "likePost"
      | "posts"
      | "profileContract"
      | "tokenContract"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PostCreated" | "PostLiked" | "RewardIssued"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LIKE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARD_PER_LIKE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "createPost", values: [string]): string;
  encodeFunctionData(
    functionFragment: "hasLiked",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "likePost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "posts", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "profileContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenContract",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "LIKE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_PER_LIKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasLiked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "likePost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "posts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "profileContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenContract",
    data: BytesLike
  ): Result;
}

export namespace PostCreatedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    author: AddressLike,
    contentHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    postId: bigint,
    author: string,
    contentHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    postId: bigint;
    author: string;
    contentHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostLikedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    liker: AddressLike,
    newLikeCount: BigNumberish
  ];
  export type OutputTuple = [
    postId: bigint,
    liker: string,
    newLikeCount: bigint
  ];
  export interface OutputObject {
    postId: bigint;
    liker: string;
    newLikeCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardIssuedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    author: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [postId: bigint, author: string, amount: bigint];
  export interface OutputObject {
    postId: bigint;
    author: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlocXSocial extends BaseContract {
  connect(runner?: ContractRunner | null): BlocXSocial;
  waitForDeployment(): Promise<this>;

  interface: BlocXSocialInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LIKE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  REWARD_PER_LIKE: TypedContractMethod<[], [bigint], "view">;

  createPost: TypedContractMethod<[_contentHash: string], [void], "nonpayable">;

  hasLiked: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  likePost: TypedContractMethod<[_postId: BigNumberish], [void], "nonpayable">;

  posts: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint] & {
        id: bigint;
        author: string;
        contentHash: string;
        likeCount: bigint;
        rewardMilestone: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  profileContract: TypedContractMethod<[], [string], "view">;

  tokenContract: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LIKE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REWARD_PER_LIKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createPost"
  ): TypedContractMethod<[_contentHash: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hasLiked"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "likePost"
  ): TypedContractMethod<[_postId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "posts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint] & {
        id: bigint;
        author: string;
        contentHash: string;
        likeCount: bigint;
        rewardMilestone: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "profileContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenContract"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "PostCreated"
  ): TypedContractEvent<
    PostCreatedEvent.InputTuple,
    PostCreatedEvent.OutputTuple,
    PostCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PostLiked"
  ): TypedContractEvent<
    PostLikedEvent.InputTuple,
    PostLikedEvent.OutputTuple,
    PostLikedEvent.OutputObject
  >;
  getEvent(
    key: "RewardIssued"
  ): TypedContractEvent<
    RewardIssuedEvent.InputTuple,
    RewardIssuedEvent.OutputTuple,
    RewardIssuedEvent.OutputObject
  >;

  filters: {
    "PostCreated(uint256,address,string,uint256)": TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;
    PostCreated: TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;

    "PostLiked(uint256,address,uint256)": TypedContractEvent<
      PostLikedEvent.InputTuple,
      PostLikedEvent.OutputTuple,
      PostLikedEvent.OutputObject
    >;
    PostLiked: TypedContractEvent<
      PostLikedEvent.InputTuple,
      PostLikedEvent.OutputTuple,
      PostLikedEvent.OutputObject
    >;

    "RewardIssued(uint256,address,uint256)": TypedContractEvent<
      RewardIssuedEvent.InputTuple,
      RewardIssuedEvent.OutputTuple,
      RewardIssuedEvent.OutputObject
    >;
    RewardIssued: TypedContractEvent<
      RewardIssuedEvent.InputTuple,
      RewardIssuedEvent.OutputTuple,
      RewardIssuedEvent.OutputObject
    >;
  };
}
