/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BlocXFollowInterface extends Interface {
  getFunction(
    nameOrSignature: "follow" | "following" | "unfollow"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Followed" | "Unfollowed"): EventFragment;

  encodeFunctionData(functionFragment: "follow", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "following",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unfollow",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "follow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "following", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unfollow", data: BytesLike): Result;
}

export namespace FollowedEvent {
  export type InputTuple = [follower: AddressLike, followed: AddressLike];
  export type OutputTuple = [follower: string, followed: string];
  export interface OutputObject {
    follower: string;
    followed: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnfollowedEvent {
  export type InputTuple = [follower: AddressLike, unfollowed: AddressLike];
  export type OutputTuple = [follower: string, unfollowed: string];
  export interface OutputObject {
    follower: string;
    unfollowed: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlocXFollow extends BaseContract {
  connect(runner?: ContractRunner | null): BlocXFollow;
  waitForDeployment(): Promise<this>;

  interface: BlocXFollowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  follow: TypedContractMethod<[target: AddressLike], [void], "nonpayable">;

  following: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  unfollow: TypedContractMethod<[target: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "follow"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "following"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "unfollow"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Followed"
  ): TypedContractEvent<
    FollowedEvent.InputTuple,
    FollowedEvent.OutputTuple,
    FollowedEvent.OutputObject
  >;
  getEvent(
    key: "Unfollowed"
  ): TypedContractEvent<
    UnfollowedEvent.InputTuple,
    UnfollowedEvent.OutputTuple,
    UnfollowedEvent.OutputObject
  >;

  filters: {
    "Followed(address,address)": TypedContractEvent<
      FollowedEvent.InputTuple,
      FollowedEvent.OutputTuple,
      FollowedEvent.OutputObject
    >;
    Followed: TypedContractEvent<
      FollowedEvent.InputTuple,
      FollowedEvent.OutputTuple,
      FollowedEvent.OutputObject
    >;

    "Unfollowed(address,address)": TypedContractEvent<
      UnfollowedEvent.InputTuple,
      UnfollowedEvent.OutputTuple,
      UnfollowedEvent.OutputObject
    >;
    Unfollowed: TypedContractEvent<
      UnfollowedEvent.InputTuple,
      UnfollowedEvent.OutputTuple,
      UnfollowedEvent.OutputObject
    >;
  };
}
