/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BlocXFollow } from "./BlocXFollow";
export type { BlocXGovernance } from "./BlocXGovernance";
export type { BlocXProfile } from "./BlocXProfile";
export type { BlocXSocial } from "./BlocXSocial";
export type { BlocXToken } from "./BlocXToken";
