/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BlocXFollow__factory } from "./BlocXFollow__factory";
export { BlocXGovernance__factory } from "./BlocXGovernance__factory";
export { BlocXProfile__factory } from "./BlocXProfile__factory";
export { BlocXSocial__factory } from "./BlocXSocial__factory";
export { BlocXToken__factory } from "./BlocXToken__factory";
